config/routes.rb
Rails.application.routes.draw do
  resources :assessments
  devise_for :users
  root to: 'page#home'
  get '/my_assessments', to: 'assessments#my_assessments'
  post '/assessments/:assessment_id/new_assignment', to: 'assessments#new_assignment', as: 'new_assignment'
  delete '/assessments/:assessment_id/destroy_assignment', to: 'assessments#remove_assignment', as: 'remove_assignment'
  get '/users', to: 'page#users'  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/user/:uuid', to: 'page#user', as: 'profile'
  post '/user/:uuid/update_role', to: 'page#update_role', as: 'update_role'
end

app/models/active_assessment.rb
class ActiveAssessment < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assessment.rb
class Assessment < ApplicationRecord
  belongs_to :created_by, class_name: 'User', foreign_key: 'created_by_id'
  has_many :questions

  validates :name, :presence => true, :uniqueness => {:scope => :name}

  accepts_nested_attributes_for :questions, reject_if: :all_blank, allow_destroy: true
  
  has_many :assigned_assessments, class_name: 'AssignedAssessment', foreign_key: 'assessment_id'
end

app/models/assigned_assessment.rb
class AssignedAssessment < ApplicationRecord
  belongs_to :assessment
  belongs_to :user
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :assessment
end

app/models/user.rb
class User < ApplicationRecord
  uuidable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :assessments, class_name: 'Assessment', foreign_key: 'created_by_id'
  has_many :assigned_assessments, class_name: 'AssignedAssessment', foreign_key: 'user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  FIELDS = [
    :first_name, :last_name, :dob, :phone, :occupation, :address, :bio, :email,
    :password, :password_confirmation, :current_password
  ]

  protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(FIELDS) }
        devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(FIELDS) }
    end
end

app/controllers/assessments_controller.rb
class AssessmentsController < ApplicationController
  before_action :set_assessment, only: %i[ show edit update destroy ]

  # GET /assessments or /assessments.json
  def index
    @assessments = Assessment.all
  end

  # GET /assessments/1 or /assessments/1.json
  def show
  end

  # GET /assessments/new
  def new
    @assessment = Assessment.new
  end

  # GET /assessments/1/edit
  def edit
  end

  # POST /assessments or /assessments.json
  def create
    @assessment = Assessment.new(assessment_params)

    respond_to do |format|
      if @assessment.save
        format.html { redirect_to @assessment, notice: "Assessment was successfully created." }
        format.json { render :show, status: :created, location: @assessment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assessments/1 or /assessments/1.json
  def update
    respond_to do |format|
      if @assessment.update(assessment_params)
        format.html { redirect_to @assessment, notice: "Assessment was successfully updated." }
        format.json { render :show, status: :ok, location: @assessment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @assessment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assessments/1 or /assessments/1.json
  def destroy
    @assessment.destroy
    respond_to do |format|
      format.html { redirect_to assessments_url, notice: "Assessment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def my_assessments
    @assessments = current_user.assigned_assessments
  end

  def new_assignment
    assessment = Assessment.find params[:assessment_id]
    user_ids = params[:assignments].keys.map {|i| !i.include?("_") ? i : nil}.compact
    users = User.where(id: user_ids)
    
    users.each do |user|
      if params[:assignments][:"#{user.id}_assign"] == "1"
        AssignedAssessment.create({ assessment_id: assessment.id, user_id: user.id })
      end
    end

    redirect_to request.referrer + "#assignments"
  end

  def remove_assignment
    assessment = Assessment.find params[:assessment_id]
    user_ids = params[:assignments].keys.map {|i| !i.include?("_") ? i : nil}.compact
    assignments = AssignedAssessment.where(assessment_id: assessment.id, user_id: user_ids)
    
    assignments.each do |a| 
      a.destroy if params[:assignments][:"#{a.user_id}_assign"] == "1"
    end

    redirect_to request.referrer + "#assignments"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assessment
      @assessment = Assessment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def assessment_params
      params.require(:assessment).permit(:name, :desc, :active, :created_by_id, questions_attributes: [:id, :question, :assessment_id, :caption, :option_type])
    end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  def home
    if current_user
      authorize current_user
      @users = User.all
      @assessments = Assessment.all
    else
      redirect_to new_user_session_path
    end
  end

  def users
    @users = authorize User.all
  end

  def user
    @user = authorize User.find params[:uuid]
  end

  def update_role
    user = User.find params[:uuid]
    user.admin = params[:update_role][:role] == "Admin"
    user.save

    redirect_to request.referrer
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  active_scaffold :"question" do |conf|
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assessments_helper.rb
module AssessmentsHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/assessments/_form.html.haml
= form_for @assessment do |f|
  - if @assessment.errors.any?
    #error_explanation
      %h2= "#{pluralize(@assessment.errors.count, "error")} prohibited this assessment from being saved:"
      %ul
        - @assessment.errors.full_messages.each do |message|
          %li= message

  .container-fluid.pt-4
    .form-group.row
      = f.label :name, "Assessment Name: ", class: 'col-lg-2'
      .col-lg-10
        = f.text_field :name, class: 'form-control'
    .form-group.row
      = f.label :desc, "Description: ", class: 'col-lg-2'
      .col-lg-10
        = f.text_area :desc, class: 'form-control', rows: 8
    .form-group 
      #questions
        %h5 Questions
        = f.fields_for :questions do |question|
          = render 'question_fields', f: question
        .links.mt-4
          = link_to_add_association "<i class='fa fa-plus'></i> Add Question".html_safe, f, :questions, class: 'btn btn-info'

    = f.hidden_field :created_by_id, value: current_user.id
  .actions.mt-4.pt-4.float-right
    .row
      .col-lg-7.pt-2
        = f.label :active, "Activate", class: ''
        = f.check_box :active, checked: true, class: ''
      .col-lg-5
        = f.submit 'Save', class: 'btn btn-info'

app/views/assessments/_question_fields.html.haml
.nested-fields.row{style: 'width:100%;'}
  .field.col-lg-6
    = f.label :question
    = f.text_field :question, class: 'form-control'
  .field.col-lg-3
    = f.label :caption
    = f.text_field :caption, class: 'form-control'
  .field.col-lg-2
    = f.label :option_type
    = f.select :option_type, options_for_select(["Agree/Disagree", "1-5", "1-10", "Yes/No", "Yes/No/Maybe"]), {}, class: 'form-control'
  .field.col-lg-1.mt-4.pt-2.text-center
    = link_to_remove_association "<i class='fa fa-times fa-2x text-danger'></i>".html_safe, f

app/views/assessments/edit.html.haml
%h1 Editing assessment

= render 'form'

app/views/assessments/index.html.haml
- content_for(:page_title, "All Assessments")

%h1 Listing assessments

%table.table
  %thead
    %tr
      %th Name
      %th Desc
      %th.text-center Active
      %th Created by
  %tbody
    - @assessments.each do |assessment|
      %tr
        %td
          .dropdown{:style => 'border: 1px solid silver;border-radius: 5px;'}
            %button#dropdownMenuButton.btn.btn-default.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :type => "button"}
              = assessment.name
            .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
              = link_to 'View', assessment, class: 'dropdown-item'
              = link_to 'Edit', edit_assessment_path(assessment), class: 'dropdown-item'
        %td.text= assessment.desc&.truncate(20)
        %td.text.text-center= assessment.active ? "<i class='fa fa-dot-circle text-success'></i>".html_safe : "<i class='fa fa-dot-circle text-danger'></i>".html_safe
        %td.text= assessment.created_by&.email
%br

= link_to 'New Assessment', new_assessment_path, class: 'btn btn-success'

app/views/assessments/my_assessments.html.haml
- content_for(:page_title, "All Assessments")

%h1 My Assessments

%table.table
  %thead
    %tr
      %th Name
      %th Desc
      %th.text-center Active
      %th.text-center Status
      %th Created by
  %tbody
    - @assessments.each do |assignment|
      %tr
        %td= assignment.assessment.name
        %td= assignment.assessment.desc&.truncate(20)
        %td.text-center= assignment.assessment.active ? "<i class='fa fa-dot-circle text-success'></i>".html_safe : "<i class='fa fa-dot-circle text-danger'></i>".html_safe
        %td.text-center= assignment.status
        %td= assignment.assessment.created_by&.email
%br

= link_to 'New Assessment', new_assessment_path

app/views/assessments/new.html.haml
%h1 New assessment

= render 'form'

app/views/assessments/show.html.haml
:css
  .dataTables_length {
    display: none;
  }

%p#notice= notice

.card
  .card-header
    %h4 Details
  .card-body
    .row
      .col-6
        %p
          %b Name:
          = @assessment.name
        %p
          %b Desc:
          = @assessment.desc
        %p
          %b Active:
          = @assessment.active
        %p
          %b Created by:
          = @assessment.created_by&.email
        %p
          %b Questions:
          %br
          - @assessment.questions.each_with_index do |question, index|
            %i= "#{index + 1}. #{question.question} #{question.caption.present? ? '[' : ''}#{question.caption}#{question.caption.present? ? ']' : ''}:<br/><strong class='ml-4'>#{question.option_type}</strong>".html_safe
            %br
.card#assignments
  .card-header
    .float-left
      %h4 Assigned Assessments
  .card-body
    .row
      .col-lg-6
        .card
          = form_for(:assignments, url: new_assignment_path(assessment_id: @assessment.id), method: :post) do |f|
            .card-header
              %h4 Available Users
            .card-body
              %table.table.table-responsive
                %thead
                  %tr
                    %th{:style => 'width: 10%;'} ID
                    %th Email
                %tbody
                  - User.all.each do |user|
                    - unless @assessment.assigned_assessments.map(&:user_id).include?(user.id)
                      %tr
                        = f.hidden_field :"#{user.id}", value: user.id
                        %td= f.check_box :"#{user.id}_assign"
                        %td= user.email
            .card-footer
              = f.submit "Assign", class: 'btn btn-info float-right mb-2'
      .col-lg-6
        .card
          = form_for(:assignments, url: remove_assignment_path(assessment_id: @assessment.id), method: :delete) do |f|
            .card-header
              %h4 Assigned Users
            .card-body
              %table.table.table-responsive
                %thead
                  %tr
                    %th{:style => 'width: 10%;'} ID
                    %th Email
                %tbody
                  - User.all.each do |user|
                    - if @assessment.assigned_assessments.map(&:user_id).include?(user.id)
                      %tr
                        = f.hidden_field :"#{user.id}", value: user.id
                        %td= f.check_box :"#{user.id}_assign"
                        %td= user.email
            .card-footer
              = f.submit "Remove", class: 'btn btn-danger float-right mb-2'
              
.row
  .col-12
    = link_to 'Edit', edit_assessment_path(@assessment)
    \|
    = link_to 'Back', assessments_path

app/views/layouts/_header.html.haml
%header.c-header.c-header-light.c-header-fixed#mainNav
  %button.c-header-toggler.c-class-toggler.d-lg-none.mfe-auto{"data-class" => "c-sidebar-show", "data-target" => "#sidebar", :type => "button"}
    %i.fas.fa-bars
  %button.c-header-toggler.c-class-toggler.mfs-3.d-md-down-none{"data-class" => "c-sidebar-lg-show", "data-target" => "#sidebar", :responsive => "true", :type => "button"}
    %i.fas.fa-bars
  
  %ul.c-header-nav.ml-auto.mr-4
    - if current_user
      %li.c-header-nav-item.d-md-down-none.mx-2
        %p{:style => 'margin-bottom:0px;'}
          Logged in:
          = current_user&.email
      %li.c-header-nav-item.dropdown
        %a.c-header-nav-link{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
          Account
        .dropdown-menu.dropdown-menu-right.pt-0
          .dropdown-header.bg-light.py-2
            %strong Options
          = link_to edit_user_registration_path, class: 'dropdown-item' do
            %i.fas.fa-user.c-sidebar-nav-icon
            Details
          = link_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
            %i.fas.fa-sign-out-alt.c-sidebar-nav-icon
            Logout

app/views/layouts/_sidebar.html.haml
#sidebar.c-sidebar.c-sidebar-dark.c-sidebar-fixed.c-sidebar-lg-show
  .c-sidebar-brand.d-md-down-none
    %i.fas.fa-home
    %span.c-sidebar-brand-full= "&nbsp;CLINIC APP".html_safe
  %ul.c-sidebar-nav
    - unless current_user
      %li.c-sidebar-nav-item
        = link_to new_user_session_path, class: 'c-sidebar-nav-link' do
          %i.fas.fa-sign-in-alt.c-sidebar-nav-icon
          Login
      %li.c-sidebar-nav-item
        = link_to new_user_registration_path, class: 'c-sidebar-nav-link' do
          %i.fas.fa-user-plus.c-sidebar-nav-icon
          Sign Up
    - else
      %li.c-sidebar-nav-title= "&nbsp;GENERAL".html_safe
      %li.c-sidebar-nav-item
        = link_to root_path, class: 'c-sidebar-nav-link' do
          %i.fas.fa-home.c-sidebar-nav-icon
          Home
      - if policy(current_user).users?
        %li.c-sidebar-nav-item
          = link_to users_path, class: 'c-sidebar-nav-link' do
            %i.fas.fa-users.c-sidebar-nav-icon
            Users
      - if policy(current_user).assessments?
        %li.c-sidebar-nav-item
          = link_to assessments_path, class: 'c-sidebar-nav-link' do
            %i.fas.fa-list-alt.c-sidebar-nav-icon
            Assessments
      %li.c-sidebar-nav-item
        = link_to my_assessments_path, class: 'c-sidebar-nav-link' do
          %i.fas.fa-list.c-sidebar-nav-icon
          My Assessments
      %li.c-sidebar-nav-title= "&nbsp;ACCOUNT".html_safe
      %li.c-sidebar-nav-item
        = link_to edit_registration_path(current_user), class: 'c-sidebar-nav-link' do
          %i.fas.fa-user-alt.c-sidebar-nav-icon
          Profile
        = link_to destroy_user_session_path, class: 'c-sidebar-nav-link' do
          %i.fas.fa-sign-out-alt.c-sidebar-nav-icon
          Logout

  %button.c-sidebar-minimizer.c-class-toggler{"data-class" => "c-sidebar-minimized", "data-target" => "_parent", :type => "button"}

app/views/layouts/application.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %meta{:content => "text/html; charset = iso-8859-1", "http-equiv" => "Content-Type"}/
    %meta{:content => "en-us", "http-equiv" => "Content-Language"}/
    %meta{:content => "width=device-width, initial-scale=1", :name => "viewport"}/
    %title Clinic App

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    
    %link{:href => "https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"}
    %script{:src => "https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"}
    %link{:href => "https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/css/select2.min.css", :rel => "stylesheet"}/
    %script{:src => "https://cdn.jsdelivr.net/npm/select2@4.1.0-beta.1/dist/js/select2.min.js"}
    %script{:crossorigin => "anonymous", :src => "https://kit.fontawesome.com/831259ec93.js"}
    %link{:href => "https://coreui.io/demo/free/3.4.0/css/style.css", :rel => "stylesheet"}/
    %link{:href => "https://cdn.datatables.net/1.11.3/css/jquery.dataTables.css", :rel => "stylesheet", :type => "text/css"}/
    %script{:charset => "utf8", :src => "https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js", :type => "text/javascript"}
    %script{:charset => "utf8", :src => "https://cdn.datatables.net/responsive/2.2.9/js/dataTables.responsive.min.js", :type => "text/javascript"}

  %body.c-app
    = render partial: 'layouts/sidebar'
    .c-wrapper
      = render partial: 'layouts/header'
      .c-body
        %main.c-main
          .c-body
            %main.c-main.pt-0
              .container-fluid
                .fade-in
                  .card
                    %h5.card-header= content_for?(:page_title) ? content_for(:page_title) : "#{controller.action_name} #{controller.controller_name.singularize}".titleize
                    .card-body
                      = yield
  
  = javascript_include_tag "https://cdn.jsdelivr.net/npm/signature_pad@2.3.2/dist/signature_pad.min.js", "https://cdn.jsdelivr.net/npm/jquery-validation@1.19.3/dist/jquery.validate.js", "https://coreui.io/demo/free/3.4.0/vendors/@coreui/coreui/js/coreui.bundle.min.js", "https://cdn.jsdelivr.net/npm/chart.js@3.5.0/dist/chart.min.js"

app/views/page/home.html.haml
- content_for(:page_title, "Home")

- if current_user.admin?
  %h1 All Users
  %table.table
    %thead
      %tr
        %th Email
        %th Role
        %th Assessments
        %th Signed Up
    %tbody
      - @users.each do |user|
        %tr
          %td.text= link_to user.email, profile_path(uuid: user.uuid), class: "#{user == current_user ? 'text-danger' : 'text-default'}"
          %td
            - if policy(user).update_role?
              = form_for(:update_role, url: update_role_path(uuid: user.uuid), html: { method: :post }) do |f|
                = f.select :role, options_for_select(['Admin', 'Client'], user.admin? ? 'Admin' : 'Client'), {}, class: 'form-control role_select'
            - else
              = form_for(:update_role, url: update_role_path(uuid: user.uuid), html: { method: :post }) do |f|
                = f.select :role, options_for_select(user.admin? ? ['Admin'] : ['Client'], user.admin? ? 'Admin' : 'Client'), {}, class: 'form-control role_select', disabled: true
          %td.text= user.assigned_assessments.map{|aa| '<a href="'+ assessment_path(aa.assessment) + '" target="_blank">' + aa.assessment.name + '</a>' }.join(", ").html_safe
          %td.text= user.created_at.strftime('%Y-%m-%d %H:%M')

  %br
  %br
  %hr
  %br
  %br


  %h1 Listing assessments
  %table.table
    %thead
      %tr
        %th Name
        %th Desc
        %th.text-center Active
        %th Created by
    %tbody
      - @assessments.each do |assessment|
        %tr
          %td
            .dropdown{:style => 'border: 1px solid silver;border-radius: 5px;'}
              %button#dropdownMenuButton.btn.btn-default.dropdown-toggle{"aria-expanded" => "false", "data-toggle" => "dropdown", :type => "button"}
                = assessment.name
              .dropdown-menu{"aria-labelledby" => "dropdownMenuButton"}
                = link_to 'View', assessment, class: 'dropdown-item'
                = link_to 'Edit', edit_assessment_path(assessment), class: 'dropdown-item'
          %td.text= assessment.desc&.truncate(20)
          %td.text.text-center= assessment.active ? "<i class='fa fa-dot-circle text-success'></i>".html_safe : "<i class='fa fa-dot-circle text-danger'></i>".html_safe
          %td.text= assessment.created_by&.email
  %br

  = link_to 'New Assessment', new_assessment_path, class: 'btn btn-success'
- else
  %p under construction

:javascript
  $(function(){
    $('.table').on('change', '.role_select', function(){
      $(this).parent('form').submit();
    });
  });

app/views/page/user.html.haml
.container-fluid
  .main-body
    .row.gutters-sm
      .col-md-4.mb-3
        .card
          .card-body
            .d-flex.flex-column.align-items-center.text-center
              %img.rounded-circle{:alt => "Admin", :src => "https://bootdey.com/img/Content/avatar/avatar7.png", :width => "150"}/
              .mt-3
                %h4= "#{@user.first_name} #{@user.last_name}"
                %p.text-secondary.mb-1= @user.occupation
                %p.text-muted.font-size-sm= @user.address
      .col-md-8
        .card.mb-3
          .card-body
            %h3.d-flex.align-items-center.mb-3
              User Details
            .row
              .col-sm-3
                %h6.mb-0 Full Name
              .col-sm-9.text-secondary
                = "#{@user.first_name} #{@user.last_name}"
            %hr/
            .row
              .col-sm-3
                %h6.mb-0 Email
              .col-sm-9.text-secondary
                = @user.email
            %hr/
            .row
              .col-sm-3
                %h6.mb-0 Phone
              .col-sm-9.text-secondary
                = @user.phone

            %hr/
            .row
              .col-sm-3
                %h6.mb-0 Address
              .col-sm-9.text-secondary
                = @user.address
            - if policy(@user).can_edit?
              %hr/
              .row
                .col-sm-12
                  = link_to 'Edit', edit_registration_path(@user), class: 'btn btn-info'
        .row.gutters-sm
          .col-sm-12.mb-3
            .card.h-100
              .card-body
                %h3.d-flex.align-items-center.mb-3
                  Current Assigned Assessments  
                %table.table
                  %thead
                    %tr
                      %th ID
                      %th Assessment Name
                      %th Completed %
                      %th Assigned At
                  %tbody
                    - @user.assigned_assessments.each_with_index do |aa, i|
                      %tr
                        %td= "#0000" + aa.id.to_s
                        %td= aa.assessment&.name
                        %td
                          %small= "#{(i + 1) * 25}%"
                          .progress.mb-3{:style => "height: 5px"}
                            .progress-bar.bg-success{"aria-valuemax" => "100", "aria-valuemin" => "0", "aria-valuenow" => "#{(i + 1) * 25}", :role => "progressbar", :style => "width: #{(i + 1) * 25}%"}
                        %td= aa.created_at.to_date

app/views/page/users.html.haml
%table.table
  %thead
    %tr
      %th Email
      %th Role
      %th Assessments
      %th Signed Up
  %tbody
    - @users.each do |user|
      %tr
        %td.text= link_to user.email, profile_path(uuid: user.uuid), class: "#{user == current_user ? 'text-danger' : 'text-default'}"
        %td
          - if policy(user).update_role?
            = form_for(:update_role, url: update_role_path(uuid: user.uuid), html: { method: :post }) do |f|
              = f.select :role, options_for_select(['Admin', 'Client'], user.admin? ? 'Admin' : 'Client'), {}, class: 'form-control role_select'
          - else
            = form_for(:update_role, url: update_role_path(uuid: user.uuid), html: { method: :post }) do |f|
              = f.select :role, options_for_select(user.admin? ? ['Admin'] : ['Client'], user.admin? ? 'Admin' : 'Client'), {}, class: 'form-control role_select', disabled: true
        %td.text= user.assigned_assessments.map{|aa| '<a href="'+ assessment_path(aa.assessment) + '" target="_blank">' + aa.assessment.name + '</a>' }.join(", ").html_safe
        %td.text= user.created_at.strftime('%Y-%m-%d %H:%M')

:javascript
  $(function(){
    $('.table').on('change', '.role_select', function(){
      $(this).parent('form').submit();
    });
  });